### PR TITLE
feat: [#4] - Update for swagger documentation

### LINKED ISSUE #2: [backend]: Setup swagger documentation for backend directory
#  Setup swagger documentation for backend directory

## Description

Please describe the issue you’re facing in as much detail as possible.

## Expected behavior

* Setup swagger documentation for nestjs application
* Create a dummy api to be displayed on swagger doc
* publish the swagger doc on `/api` route.

### PR DESCRIPTION
**Pull request by DatHoang102003**
# Pull Request Template

## Description

Please include a summary of the changes and the related issue.

Fixes #2 

## Type of Change

- [ ] Bug fix
- [Add swagger documentation] New feature
- [ ] Breaking change

## Checklist

- [ ✓] I have read the contribution guidelines.
- [ ✓] I have followed the code style guidelines.
- [ ✓] I have added tests that prove my fix is effective or that my feature works.
- [ ✓] All new and existing tests passed.

## Screenshots (if applicable)

Attach screenshots to better demonstrate the changes, if applicable.

### CODE REVIEW

**Comment by DatHoang102003** [comment]
Oh and here is the screenshot:
image

**Review by akbatra567 — CHANGES_REQUESTED** [review]
Hey @DatHoang102003, 
Could you remove comments ? The code is self explanatory hence comments are not needed.

**Comment by akbatra567** [comment]
@DatHoang102003 
Also could you change the PR name as per template ?

```
Example: 'feat: [#123] - my title'
```

**Comment by DatHoang102003** [comment]
I've updated the code and the PR title as per your request. Could you please review it for merging?

**Review by akbatra567 — APPROVED** [review]

**Pull request merged**
